// scripts/check_types.ts
//
// Checks the declared response types against real responses. `deno task smoke` saves every response to
// fixtures/<api>.<function>.json; this script assigns each fixture to the declared return type of its endpoint and
// type-checks the result, so every error is a place where the types and the live API disagree
// (a required field that is missing, or a field with the wrong type). Fields the types don't declare are not reported.
//
// Usage:
//   deno task check:types [filter]

import { dirname, fromFileUrl, join } from "@std/path";

const root = join(dirname(fromFileUrl(import.meta.url)), "..");
const fixturesDir = join(root, "fixtures");
const checkFile = join(fixturesDir, "_typecheck.ts");

/** Fixture prefix -> generated API interface and its module. */
const apis: Record<string, { type: string; module: string }> = {
    wow: { type: "WowApi", module: "wow_api.ts" },
    wowClassic: { type: "WowClassicApi", module: "wow_classic_api.ts" },
    wowClassicEra: { type: "WowClassicEraApi", module: "wow_classic_era_api.ts" },
    hearthstone: { type: "HearthstoneApi", module: "hearthstone_api.ts" },
    sc2: { type: "Sc2Api", module: "sc2_api.ts" },
    diablo3: { type: "Diablo3Api", module: "diablo3_api.ts" },
};

/** Very large responses (e.g. commodities) make the type checker slow without adding coverage. */
const MAX_FIXTURE_BYTES = 2_000_000;

const filter = Deno.args[0] ?? "";
const lines: string[] = [];
const caseByLine = new Map<number, string>();
const header = [
    "// Generated by scripts/check_types.ts. Do not edit.",
    ...Object.values(apis).map(({ type, module }) => `import type { ${type} } from "../src/generated/${module}";`),
    "// deno-lint-ignore no-explicit-any",
    "type R<F> = F extends (...args: any[]) => Promise<infer T> ? T : never;",
];

let index = 0;
for await (const entry of Deno.readDir(fixturesDir)) {
    const match = entry.name.match(/^(\w+)\.(\w+)\.json$/);
    if (!entry.isFile || !match) continue;
    const [, prefix, fn] = match;
    const api = apis[prefix];
    const name = `${prefix}.${fn}`;
    if (!api || !name.includes(filter)) continue;
    if ((await Deno.stat(join(fixturesDir, entry.name))).size > MAX_FIXTURE_BYTES) {
        console.log(`skipped (too large): ${name}`);
        continue;
    }
    const id = `f${index++}`;
    lines.push(`import ${id} from "./${entry.name}" with { type: "json" };`);
    lines.push(`const _${id}: R<${api.type}["${fn}"]> = ${id};`);
    caseByLine.set(header.length + lines.length, name);
}

await Deno.writeTextFile(checkFile, [...header, ...lines].join("\n") + "\n");

const { stdout, stderr } = await new Deno.Command(Deno.execPath(), {
    args: ["check", "--quiet", checkFile],
    env: { NO_COLOR: "1" },
    cwd: root,
}).output();
const output = new TextDecoder().decode(stdout) + new TextDecoder().decode(stderr);

// Group the diagnostics by fixture. Each diagnostic starts with "TS<code> [ERROR]" and ends with an "at <file>:<line>".
const problems = new Map<string, string[]>();
for (const block of output.split(/\n(?=TS\d+ \[ERROR\])/)) {
    const at = block.match(/_typecheck\.ts:(\d+):\d+/);
    if (!at) continue;
    const name = caseByLine.get(Number(at[1])) ?? `line ${at[1]}`;
    const message = block.split("\n").filter((line) =>
        line.trim() && !line.includes("_typecheck.ts") && !/^\s*~+\s*$/.test(line) && !line.includes("= f")
    ).map((line) => line.trimEnd()).join("\n");
    problems.set(name, [...(problems.get(name) ?? []), message]);
}

/** Keeps the start and the end of long diagnostics: the root cause of a mismatch is in the last lines. */
function shorten(message: string): string {
    const lines = message.split("\n").map((line) => line.length > 300 ? line.slice(0, 300) + "…" : line);
    return lines.length > 12 ? [...lines.slice(0, 4), "    …", ...lines.slice(-8)].join("\n") : lines.join("\n");
}

const checked = caseByLine.size;
for (const [name, messages] of [...problems].sort()) {
    console.log(`\n=== ${name}`);
    for (const message of messages) console.log(shorten(message));
}
console.log(`\nChecked ${checked} fixtures: ${checked - problems.size} match, ${problems.size} with type errors.`);
if (problems.size) Deno.exit(1);
