# .github/workflows/check.yml
name: Check
on:
    push:
        branches: [main]
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - run: deno fmt --check
            - run: deno lint
            - run: deno check mod.ts scripts/*.ts tests/*.ts
            - run: deno test
            - run: deno task gen:api --check
            - run: deno publish --dry-run --allow-dirty
